FROM golang:latest AS builder
WORKDIR /app
COPY go.mod ./
COPY . .
RUN go mod download
RUN go build ./cmd/p1oneer

FROM debian:latest
WORKDIR /init
ENV P1ONEER_CONFIG_DIR=/init/p1-configs
COPY ./examples/*.json /init/p1-configs/
COPY --from=builder /app/p1oneer .
RUN apt update && apt install -y php-fpm nginx
ENTRYPOINT [ "./p1oneer" ]
